### ISSUE TITLE
[Github Actions][Feature request] Build apk and ios app with artifacts

### ISSUE THREAD

**Issue by pablodz** [jaysavsani07/FlutterBMI#2]
Hello guys, you can add automatic builder in
`.github/workflows/builder.yml`

with this lines

```
# This is a basic workflow to help you get started with Actions

name: Builder APK, APPBUNDLE AND IOS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildUbuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    
  buildMacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign

    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-ios
        path: /Users/runner/work/app/app/build/ios/iphoneos/Runner.app
```

and you'll get something like this on each push

![image](https://user-images.githubusercontent.com/28235457/118509617-d0b99c80-b6f5-11eb-9b1a-632e77a39e9c.png)
